### ISSUE TITLE
Image Read Hook

### ISSUE THREAD

**Issue by CandidXD** [anchore/stereoscope#72]
**What would you like to be added**:
I hope the Image Read() can provide a hook for skipping read the layer what needn't read again. For example: 

```go
func (i *Image) Read(hook func(layer *Layer) bool) error {
...
	for idx, v1Layer := range v1Layers {
		layer := NewLayer(v1Layer)
		if hook(v1Layer) {
			continue
		}
		err := layer.Read(&i.FileCatalog, i.Metadata, idx, i.contentCacheDir)
		if err != nil {
			return err
		}
		i.Metadata.Size += layer.Metadata.Size
		layers = append(layers, layer)

		readProg.N++
	}
...
}
```

I hope this hook can be exposed to the func 'GetImage()'

**Why is this needed**:
With the overlay of the layer, base layer's digest is always same. In order to avoid repetitive waste of resources.

**Additional context**:

**Comment by CandidXD** [comment]
I hope this hook can be exposed to the func 'GetImage()'

**Comment by wagoodman** [comment]
Hey @CandidXD ! I'm trying to understand the use case for this hook function and the impact that it will have on the filesystem representation of the image.

It is true that when `Image.Read()` is called that all layers are read and the contents indexed. I'm trying to understand the redundant actions that you're referring to since each layer is read once and only once. 

It is important not to skip reading layers since doing so would skip indexing the filesystem for that layer. If a layer is "skipped" and any of the above layers have a whiteout file that attempts to "remove" a file from the skipped layer in the squashed representation it could be problematic (since that file never existed since the layer that does have the file was skipped).

This get's weirder with symlink/hardlink resolution --if we skip reading a layer and indexing it's contents, we have no guarantee that link resolution will function correctly (there are several cases here).

Happy to chat this one through as performance optimizations are very welcome! I'm just trying to understand the need for skipping layer reads that are currently read once (and need to be read at least once).

**Comment by CandidXD** [comment]
> Hey @CandidXD ! I'm trying to understand the use case for this hook function and the impact that it will have on the filesystem representation of the image.
> 
> It is true that when `Image.Read()` is called that all layers are read and the contents indexed. I'm trying to understand the redundant actions that you're referring to since each layer is read once and only once.
> 
> It is important not to skip reading layers since doing so would skip indexing the filesystem for that layer. If a layer is "skipped" and any of the above layers have a whiteout file that attempts to "remove" a file from the skipped layer in the squashed representation it could be problematic (since that file never existed since the layer that does have the file was skipped).
> 
> This get's weirder with symlink/hardlink resolution --if we skip reading a layer and indexing it's contents, we have no guarantee that link resolution will function correctly (there are several cases here).
> 
> Happy to chat this one through as performance optimizations are very welcome! I'm just trying to understand the need for skipping layer reads that are currently read once (and need to be read at least once).

Sorry for getting back to you so late. I describe my use case. For a project, we use Dockerfile to build a image. Usually, the base image is same. If we have 100 image, like v1.0 to v100.0, we need to parse the base layer 100 times. So, if i save the base layer's info in the first times, we need't to parse the base layer in the remaining 99. But i don't know, if i don't parse the base layer, will it affect the parsing of other layers?

**Comment by kzantow** [comment]
Hi @CandidXD -- currently Syft and related tools only scan a single image at a time and don't have any sort of cache that might be able to store an analysis of a particular base image. Is this still an issue for you somehow? We would be happy to talk about this more, if you ever had the time to join one of [the community meetings](https://docs.google.com/document/d/1ZtSAa6fj2a6KRWviTn3WoJm09edvrNUp4Iz_dOjjyY8/edit).
