### ISSUE TITLE
Concurrently analyzing containers can lead to race condition causing error

### ISSUE THREAD

**Issue by vanderpot-uber** [anchore/stereoscope#96]
**What happened**:
When using Grype as a library and scanning multiple containers in multiple goroutines, some of the goroutines may fail with an error like:
```
could not fetch image 'registry/image:tag': could not read image: failed to read layer="sha256:deadbeef" tar : open /tmp/stereoscope-cache516617993/sha256:deadbeef.tar: no such file or directory
```

**What you expected to happen**:
Multiple container images can be analyzed concurrently in the same go process.

**How to reproduce it (as minimally and precisely as possible)**:

Scan multiple containers with grype pkg.Provide in the same process.

Working on a unit test that will reliably reproduce this.

**Anything else we need to know?**:
I think this issue is caused by the temp dir generator being in module scope instead of in the scope of the stereoscope image. file.Cleanup() is called at the end of each container analysis, which will delete ALL images on disk.

https://github.com/anchore/stereoscope/blob/6e663afeef5d6a07f4b86b4dacbc79b39457468c/client.go#L16
https://github.com/anchore/stereoscope/blob/6e663afeef5d6a07f4b86b4dacbc79b39457468c/client.go#L70-L74

**Environment**:
- MacOS
- Debian

**Comment by wagoodman** [comment]
For tracking: there is a closed PR that addresses this issue that if considered, would need to be re-evaluated and cleaned up: github.com/anchore/stereoscope/pull/71

**Comment by ajvpot** [comment]
@wagoodman I quickly put together something similar to that, but didn't want to break the public api. 

Would you be open to propagating context through GetImage*? This would let you clean up when the context is canceled.

**Comment by wagoodman** [comment]
> Would you be open to propagating context through GetImage*? 

I've used that pattern before on calls where the caller is attempting to cancel the current call (in this case it would be a call to GetImage) and short-circuit execution, cleaning on the way back out of the call (either on the happy path or otherwise). However, the tempfiles that GetImage creates need to persist after this call and need to get cleaned up as part of the Image object, which means that we're tying context cancellation to something that is stored directly on the Image object --I think this goes against standard practice of context objects, where they should be ephemeral and not stored as state in structs.

I could be misinterpreting what you're suggesting too (regarding the use of context); to make certain we're on the same page I'd be up for chatting over a draft PR if you'd like 👍

**Comment by ajvpot** [comment]
After trying to implement the cleanup tied to the context, I agree with you it's probably not the best way to go. However, I still created a draft PR #99 to add a context param to GetImage* and pass it through to the `go-containerregistry` network functions. This will allow for cancellation/timeout of requests and facilitate use as a library. 

I think the approach in #71 is the way to go for handling cleanup of tmp dirs. I'd be willing to pick that up, is there anything in particular you'd like to see before it's mergeable?

**Comment by ajvpot** [comment]
Hey @wagoodman did you have a chance to look at this? Thanks!

**Comment by wagoodman** [comment]
indeed! 

#99 is a solid improvement in terms of providing cancellation control --we should definitely get that in 🎉 .

In terms of #71 there is a bit of conversation that might be needed first. The good thing with #71 is that is compartmentalizes  cleanup calls to be done for a single image, and not all images like today. This is a critical first step towards "the right way".

The "up in the air" / "bad" category here is leaving the static "catch all" cleanup function. This is leveraged by Syft today since the worker goroutine doesn't have access to the image object, thus doesn't have a way for the caller to clean up the specific image so calls the catch all `stereoscope.Cleanup()` function from the event loop. The ultimate goal is to remove the need for the catch all static cleanup function, and the question is could that be saved for a future PR or should it be addressed now (which requires syft changes).

There are a couple minor ergonomic issues with #71 (though still blocking), specifically, instead of returning a cleanup function we should probably be providing a `Cleanup()` function directly on the `image.Image` object returned.

>  I think it would be a good idea to merge both at the same time because they are both breaking changes

Though they are both breaking changes, I think it's alright (and actually preferred) to have these changes be independent of one another --I think getting #90  in now as we work on some reincarnation of #71 is alright / good 👍 .

**Comment by wagoodman** [comment]
@ajvpot I can resurrect #71 and get it into a mergable state --I'll shout out when it's up

**Comment by ajvpot** [comment]
Awesome! I'll get #99 cleaned up/CLA signed. 🙌

**Comment by wagoodman** [comment]
I'll get this incorporated into syft and grype, thanks for reporting this and working with me on it! 🙌
